import type { Denomination, Chapter, Student } from "@/types";

export const initialDenominations: Denomination[] = [
  {
    id: "pentecost",
    name: "Pentecost Students & Associates",
    description: "A Christ-centred family growing through prayer, worship and the Word.",
  },
  {
    id: "presby",
    name: "Ghana Fellowship of Evangelical Students",
    description: "A welcoming evangelical student community rooted in scripture and service.",
  },
  {
    id: "catholic",
    name: "Catholic Students' Union",
    description: "Campus Catholic life expressed through faith, friendship and service.",
  },
  {
    id: "methodist",
    name: "Methodist Students' Union",
    description: "A student fellowship shaped by warm hearts, active faith and shared life.",
  },
  {
    id: "anglican",
    name: "Anglican Students' Fellowship",
    description: "A prayerful community for worship, formation and belonging.",
  },
];

export const initialChapters: Chapter[] = [
  {
    id: "pensa-main",
    denominationId: "pentecost",
    name: "PENSA UCC",
    shortName: "PENSA",
    campus: "Main Campus",
    status: "active",
    meetingDay: "Sunday",
    meetingTime: "7:00 AM",
    location: "New Examination Centre",
    description:
      "A lively family of students learning Christ together through worship, small groups, prayer and practical care.",
    whatsapp: "https://wa.me/233000000000",
    headEmail: "head@pensa.edu.gh",
  },
  {
    id: "ghafes-main",
    denominationId: "presby",
    name: "GHAFES UCC",
    shortName: "GHAFES",
    campus: "Main Campus",
    status: "active",
    meetingDay: "Sunday",
    meetingTime: "6:30 AM",
    location: "School of Medical Sciences Auditorium",
    description:
      "Come as you are for thoughtful Bible study, worship, friendship and service on campus.",
    whatsapp: "https://wa.me/233000000001",
    headEmail: "head@ghafes.edu.gh",
  },
  {
    id: "casu-main",
    denominationId: "catholic",
    name: "CASU UCC",
    shortName: "CASU",
    campus: "Main Campus",
    status: "active",
    meetingDay: "Sunday",
    meetingTime: "7:30 AM",
    location: "St. John the Baptist Chaplaincy",
    description:
      "A home for Catholic students to celebrate Mass, deepen faith and serve together.",
    whatsapp: "https://wa.me/233000000002",
    headEmail: "head@casu.edu.gh",
  },
  {
    id: "methosa-main",
    denominationId: "methodist",
    name: "GHAMSU UCC",
    shortName: "GHAMSU",
    campus: "Main Campus",
    status: "coming-soon",
    description: "The Methodist student community at Main Campus is preparing its meeting details.",
    headEmail: "head@ghamsu.edu.gh",
  },
  {
    id: "anglican-essikado",
    denominationId: "anglican",
    name: "ASF Essikado",
    shortName: "ASF",
    campus: "Essikado",
    status: "active",
    meetingDay: "Saturday",
    meetingTime: "5:00 PM",
    location: "Essikado Campus Courtyard",
    description:
      "An intimate community of prayer, fellowship and service for students at Essikado.",
    whatsapp: "https://wa.me/233000000003",
    headEmail: "head@asf.edu.gh",
  },
  {
    id: "pensa-essikado",
    denominationId: "pentecost",
    name: "PENSA Essikado",
    shortName: "PENSA",
    campus: "Essikado",
    status: "coming-soon",
    description: "A new PENSA chapter is taking root at Essikado.",
    headEmail: "essikado@pensa.edu.gh",
  },
  {
    id: "casu-essikado",
    denominationId: "catholic",
    name: "CASU Essikado",
    shortName: "CASU",
    campus: "Essikado",
    status: "draft",
    description: "Draft chapter awaiting a chapter head.",
    headEmail: "",
  },
];

export const initialStudents: Student[] = [
  {
    id: "s1",
    name: "Ama Mensah",
    email: "ama.mensah@stu.ucc.edu.gh",
    phone: "024 561 9204",
    campus: "Main Campus",
    program: "BSc Nursing",
    hall: "Adehye Hall",
    level: "200",
    chapterId: "pensa-main",
  },
  {
    id: "s2",
    name: "Kojo Asare",
    email: "kojo.asare@stu.ucc.edu.gh",
    phone: "055 103 8842",
    campus: "Main Campus",
    program: "BA Communication",
    hall: "Atlantic Hall",
    level: "300",
    chapterId: "pensa-main",
    flagged: true,
  },
  {
    id: "s3",
    name: "Esi Nyarko",
    email: "esi.nyarko@stu.ucc.edu.gh",
    phone: "020 443 7610",
    campus: "Main Campus",
    program: "BCom Accounting",
    hall: "Valco Hall",
    level: "100",
    chapterId: "pensa-main",
  },
  {
    id: "s4",
    name: "Nana Kofi Boateng",
    email: "nana.boateng@stu.ucc.edu.gh",
    phone: "027 901 3385",
    campus: "Main Campus",
    program: "BEd Science",
    hall: "Oguaa Hall",
    level: "400",
    chapterId: "pensa-main",
  },
];
